---
apiVersion: v1
kind: Service
metadata:
  name: math
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
    nodePort: 30010
  selector:
    app: compute-api
    api: math
  type: NodePort
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: plus
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
    nodePort: 30011
  selector:
    app: compute-api
    api: plus
  type: NodePort
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: minus
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
    nodePort: 30012
  selector:
    app: compute-api
    api: minus
  type: NodePort
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: multiply
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
    nodePort: 30013
  selector:
    app: compute-api
    api: multiply
  type: NodePort
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: divide
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
    nodePort: 30014
  selector:
    app: compute-api
    api: divide
  type: NodePort
  externalTrafficPolicy: Local
