apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: computes
spec:
  rules:
  - host: compute.api
    http:
      paths:
      - path: /math
        backend:
          serviceName: math
          servicePort: 80
      - path: /plus
        backend:
          serviceName: plus
          servicePort: 80
      - path: /minus
        backend:
          serviceName: minus
          servicePort: 80
      - path: /multiply
        backend:
          serviceName: multiply
          servicePort: 80
      - path: /divide
        backend:
          serviceName: divide
          servicePort: 80